controllers:
    resource: ../src/Controller/
    type: annotation

swagappsystem_controllers:
    resource: ../src/SwagAppsystem/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
